"""add clolum for table image

Revision ID: dea156a2abd0
Revises: cada4a188012
Create Date: 2019-04-17 10:12:12.331187

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dea156a2abd0'
down_revision = 'cada4a188012'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('image', sa.Column('file_name', sa.String(length=255), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('image', 'file_name')
    # ### end Alembic commands ###
